[env:crowpanel-epaper]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ESP32-S3-WROOM-1-N8R8: 8MB flash, 8MB PSRAM
board_build.arduino.memory_type = qio_opi
board_build.psram = enabled
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^7
    me-no-dev/ESPAsyncWebServer@^1.2.4
    me-no-dev/AsyncTCP@^1.1.1
    SPI
    SD

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
